version: '3.8'

services:
  aurora-locus:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./config:/config
    environment:
      - RUST_LOG=info
      - DATABASE_URL=sqlite:///data/aurora-locus.db
      - HOSTNAME=localhost
      - PORT=3000
      - SERVICE_DID=did:web:localhost
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/xrpc/_health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
  config:
